[package]
name = "ssbot"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ssbot"
path = "src/main.rs"

[dependencies]
ssbot-engine.workspace = true
ssbot-runtime.workspace = true
ssbot-lab.workspace = true

anyhow.workspace = true
clap.workspace = true
image.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing-subscriber.workspace = true

[features]
xcap = ["ssbot-runtime/xcap"]
